#!/bin/bash

#set -eu

if [ -z $1 ]; then
    CUSTOM="no"
else
    CUSTOM="yes"
fi

# build jark without renaming the project
export LEIN_SNAPSHOTS_IN_RELEASE="yes"
export LEIN_ROOT="yes"

COMMON_COMPONENTS="bin/clj_completions bin/shflags modules/ bin/jark-client bin/simplejson.py bin/termcolor.py"
SERVER_COMPONENTS="bin/project-cljr.clj *.jar jark-deps.txt"
CLIENT_COMPONENTS="bin/jark-client"

build_server() {
    mkdir -p classes
    javac -d classes/ src/jark/SystemThreadList.java 
    if [ $? != 0 ]; then 
        echo "javac not installed, exiting"
        exit 1
    fi
    echo "Getting dependencies.."
    lein deps && lein jar

    touch jark-deps.txt
    :> jark-deps.txt
    for i in `ls lib/*.jar`; do
        echo $i >> jark-deps.txt
    done

    for i in `ls lib/*.jar`; do
        tar -rf payload.tar $i
    done
    tar -rf payload.tar ${SERVER_COMPONENTS}
}

build_client() {
    tar -rvf payload.tar ${CLIENT_COMPONENTS}
}

update_version() {
    local TMPL_COMPONENT="$1"
    echo "Updating build information"
    COMMIT=`git rev-parse --verify --short HEAD`
    DATE=`date`
    ARCH=`uname -m`
    TMPL_DATE="$DATE"
    RELEASE_VERSION=`git branch --no-color | sed -e '/^[^*]/d' -e 's/* \(.*\)/\1/'`
    echo "git hash        : $COMMIT"
    echo "arch            : $ARCH"
    echo "date            : $DATE"
    echo "component       : ${TMPL_COMPONENT}"
    echo "release version : $RELEASE_VERSION"
    perl -pi -e "s/TMPL_VERSION/$COMMIT/g" jark
    perl -pi -e "s/TMPL_ARCH/${ARCH}/g" jark
    perl -pi -e "s/TMPL_DATE/${TMPL_DATE}/g" jark
    perl -pi -e "s/TMPL_COMPONENT/${TMPL_COMPONENT}/g" jark
    perl -pi -e "s/TMPL_RELEASE_VERSION/${RELEASE_VERSION}/g" jark
    exit 0
}

generate_jark() {
    if [ -e "payload.tar" ]; then
        gzip payload.tar
        cat bin/jark.bin payload.tar.gz > jark
        rm payload.tar.gz
        chmod +x jark
        echo "jark self extracting script created"
    else
        echo "payload.tar.gz does not exist"
        exit 1
    fi
}

# begin building

echo "Adding common components ..."
tar cf payload.tar ${COMMON_COMPONENTS}

TMPL_COMPONENT="client"

if [ $CUSTOM == "no" ]; then
    echo "building both server and client components"
    TMPL_COMPONENT="server"
    build_server
    build_client
else
    if [ "$1" == "--client" ] || [ "$1" == "client" ]; then
        echo "building client components"
        TMPL_COMPONENT="client"
        build_client
    fi

    if [ "$1" == "--server" ] || [ "$1" == "server" ]; then
        echo "building server components"
        TMPL_COMPONENT="server"
        build_server
    fi
fi

generate_jark
update_version ${TMPL_COMPONENT}
exit 0




