#!/bin/bash

set -eu 

# build jark without renaming the project
LEIN_SNAPSHOTS_IN_RELEASE="yes"

if [ $? != 0 ]; then 
    echo "javac not installed, exiting"
    exit 1
fi
lein jar

touch jark-deps.txt
:> jark-deps.txt
for i in `ls lib/*.jar`; do
    echo $i >> jark-deps.txt
done

tar cf payload.tar bin/clj_completions bin/shflags bin/project-cljr.clj *.jar jark-deps.txt modules/

for i in `ls lib/*.jar`; do
    tar -rf payload.tar $i
done

if [ -e "payload.tar" ]; then
    gzip payload.tar

    if [ -e "payload.tar.gz" ]; then
        cat bin/jark.bin payload.tar.gz > jark
        rm payload.tar.gz
    else
        echo "payload.tar.gz does not exist"
        exit 1
    fi
else
    echo "payload.tar does not exist"
    exit 1
fi

echo "Updating build information"
COMMIT=`git rev-parse --verify --short HEAD`
DATE=`date`
ARCH=`uname -m`
TMPL_DATE="$ARCH | $DATE"
echo "git hash: $COMMIT"
perl -pi -e "s/TMPL_VERSION/$COMMIT/g" jark
perl -pi -e "s/TMPL_DATE/${TMPL_DATE}/g" jark

chmod +x jark
echo "jark self extracting script created"
exit 0
